version: "3.9"
services:
  # unlike the backend app, we have to attach to container and edit code directly, recommend running the angular app natively in windows and connect to the backend docker container
  react:
    build: ./frontend
    environment:
      NODE_ENV: development
    volumes:
      - ./frontend:/code
    expose:
      - 3000
    ports:
      - "3000:3000"

  # files persist via volume between host and container
  django:
    build: ./backend
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
  primary-db:
    image: mongo
    expose:
      - 27017
    ports:
      - "27017:27017"
    restart: always
    entrypoint: ["/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0"]
